spring:
  application:
    name: safe_holiday
  datasource:
    url: jdbc:mysql://awseb-e-pt7chkvyrq-stack-awsebrdsdatabase-12kwmm5wh3rg.cp66uy6emz8s.ap-northeast-2.rds.amazonaws.com:3306/testdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ebroot
    password: 20000823
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: su00082323@gmail.com
    password: qiautqpkcgypxljb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      fail-on-unknown-properties: false

server:
  port: 5000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security.web: debug