spring:
  application:
    name: safe_holiday
  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
<<<<<<<<< Temporary merge branch 1
      ddl-auto: create #
=========
      ddl-auto: update
>>>>>>>>> Temporary merge branch 2
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security.web: trace
